sampleLocations = [# ("H2hh260",     "/hdfs/store/user/elaird/nt_H2hh260_v1-SUB-TT"),
#                    ("H2hh300",     "/hdfs/store/user/elaird/nt_H2hh300_v1-SUB-TT"),
#                    ("H2hh350",     "/hdfs/store/user/elaird/nt_H2hh350_v1-SUB-TT"),
#                    ("tt_eff",      "/hdfs/store/user/elaird/nt_ttfull_v1-SUB-TT"),
#                    ("tt_semi_eff", "/hdfs/store/user/elaird/nt_ttsemi_v1-SUB-TT"),
#                    ("ZZ_eff",      "/hdfs/store/user/elaird/nt_zz_v1-SUB-TT"),
# 
                   ("H2hh270",      "/hdfs/store/user/zmao/H2hh270_newTrigger-SUB-TT"),
#                    ("H2hh280",      "/hdfs/store/user/zmao/H2hh280_newTrigger-SUB-TT"),
#                    ("H2hh290",      "/hdfs/store/user/zmao/H2hh290_newTrigger-SUB-TT"),
#                    ("H2hh310",      "/hdfs/store/user/zmao/H2hh310_newTrigger-SUB-TT"),
#                    ("H2hh320",      "/hdfs/store/user/zmao/H2hh320_newTrigger-SUB-TT"),
#                    ("H2hh330",      "/hdfs/store/user/zmao/H2hh330_newTrigger-SUB-TT"),
#                    ("H2hh340",      "/hdfs/store/user/zmao/H2hh340_newTrigger-SUB-TT"),
# 
#                    ("H2hh500",      "/hdfs/store/user/zmao/H2hh500_rad-SUB-TT"),
#                    ("H2hh700",      "/hdfs/store/user/zmao/H2hh700_rad-SUB-TT"),
#                    ("H2hh1000",      "/hdfs/store/user/zmao/H2hh1000_rad-SUB-TT"),
# 
#                    
#                   ('dataA', '/hdfs/store/user/elaird/nt_tau_A_v1-SUB-TT-data/'),
#                   ('dataB', '/hdfs/store/user/elaird/nt_tauP_B_v1-SUB-TT-data/'),
#                   ('dataC', '/hdfs/store/user/elaird/nt_tauP_C_v1-SUB-TT-data/'),
#                   ('dataD', '/hdfs/store/user/elaird/nt_tauP_D_v1-SUB-TT-data/'),
#                    ('dataTotal', '/scratch/zmao/jetPt20/data' ),

#                     ('QCD_Pt-30to50', '/hdfs/store/user/zmao/QCD_Pt-30to50_newMET-SUB-TT'),
#                     ('QCD_Pt-50to80', '/hdfs/store/user/zmao/QCD_Pt-50to80_newMET-SUB-TT'),
#                     ('QCD_Pt-80to120', '/hdfs/store/user/zmao/QCD_Pt-80to120_newMET-SUB-TT'),
#                     ('QCD-120to170', '/hdfs/store/user/zmao/QCD_Pt-120to170_newMET-SUB-TT'),
#                     ('QCD_Pt-30To50_bEnriched', '/hdfs/store/user/zmao/QCD_Pt-30To50_bEnriched_newMET-SUB-TT'),
#                     ('QCD_Pt-50To150_bEnriched', '/hdfs/store/user/zmao/QCD_Pt-50To150_bEnriched_newMET-SUB-TT'),
#                     ('QCD_Pt-150_bEnriched', '/hdfs/store/user/zmao/QCD_Pt-150_bEnriched_newMET-SUB-TT'),
#                     ('QCDtotal', '/scratch/zmao/QCD/qcd' ),
#                     ('QCDtotal_bEnriched', '/scratch/zmao/QCD/bEnriched' ),
#                     ('DYJetsToLL_eff', '/hdfs/store/user/zmao/DYJetsToLL_newMET-SUB-TT'),
#                     ('DY1JetsToLL', '/hdfs/store/user/zmao/DY1JetsToLL_newTrigger-SUB-TT'),
#                     ('DY2JetsToLL', '/hdfs/store/user/zmao/DY2JetsToLL_newTrigger-SUB-TT'),
#                     ('DY3JetsToLL', '/hdfs/store/user/zmao/DY3JetsToLL_newTrigger-SUB-TT'),
#                     ('W1JetsToLNu', '/hdfs/store/user/zmao/W1JetsToLNu_newTrigger-SUB-TT'),
#                     ('W2JetsToLNu', '/hdfs/store/user/zmao/W2JetsToLNu_newTrigger-SUB-TT'),
#                     ('W3JetsToLNu', '/hdfs/store/user/zmao/W3JetsToLNu_newTrigger-SUB-TT'),
#                     ('WZJetsTo2L2Q_eff', '/hdfs/store/user/zmao/WZJetsTo2L2Q_newMET-SUB-TT'),
#                     ('H2hh300', '/hdfs/store/user/zmao/H2hh300_pt20WithInit-SUB-TT'),
#                       ('VBF_HToTauTau', '/hdfs/store/user/zmao/VBF_HToTauTau-SUB-TT'),
#                       ('TTJets_MSDecays', '/hdfs/store/user/zmao/TTJets_MSDecays-SUB-TT'),
#                       ('GluGluToHToTauTau', '/hdfs/store/user/zmao/GluGluToHToTauTau-SUB-TT'),
#                       ('WH_ZH_TTH_HToTauTau', '/hdfs/store/user/zmao/WH_ZH_TTH_HToTauTau-SUB-TT'),
#                     ("H2hh300",  "/hdfs/store/user/zmao/H2hh300_syncNew-SUB-TT"),
#                     ("H2hh300_newTauID", "/hdfs/store/user/zmao/H2hh300_newTauID-SUB-TT"),
                  ]

jetPtThreshold = 20
corruptedROOTfiles = []
